- custom/index.md
@Ivocin @antfu @QC-L
custom/index 的翻译已完成。有一个细节是否需要约定一下：section是译为 “部分” 还是 ”章节“。一些在文档中高频出现的存在多种翻译可能的词，我们是否可以做一个约定。
> docs(cn): custom/index translation

- themes/write-a-theme.md
@Ivocin @antfu @QC-L 
- 我注意到 #14 中对于 Front Matter 的讨论，所以保留了原文，可以等确定后进行更改
- 原文中的 Capability 感觉直译比较奇怪，所以译为了 **自定义**，可以讨论是否有更合适的翻译
> docs(cn): themes/write-a-theme translation

- themes/write-a-theme.md
参考 [#18](https://github.com/slidevjs/docs-cn/pull/18#discussion_r633145125) 中的讨论对翻译进行修改。
> fix(docs): update write-a-theme translation

- custom/config-katex.md
@Ivocin @antfu @QC-L
custom/config-katex 的翻译已完成，请审核，谢谢。
> docs(cn): custom/config-katex translation

- custom/config-mermaid.md
custom/config-mermaid的翻译已经完成，请审核，谢谢。
> docs(cn): custom/config-mermaid translation

- guide/syntax.md
> docs(cn): fix translation in guide/syntax.md

- guide/install.md
原有的 docker 镜像已经无法访问到。我重新构建了一个并添加了更多使用说明
> 修改 install.md 来替换 docker 部分

- guide/install.md
> Make docker host related part more clear

- resources/learning.md
- showcases.md
The showcases and learning pages used to be in English, but now I have changed them to Chinese.
> docs(cn): Update showcases.md and learning.md

- .vitepress/showcases.ts
link: https://ppt.godkun.top/
post: https://mp.weixin.qq.com/s/sZTQJLG8gsOxBVesZ8oOJg
> docs: add slidev ppt template with naive-ui

- custom/index.md
Translating per slide configuration content for custom chapters
> docs(custom): translation per slide configuration

- builtin/components.md
- custom/config-parser.md
- custom/config-shortcuts.md
- custom/config-unocss.md
- custom/highlighters.md
- custom/vue-context.md
> docs: translate a few pages

- guide/install.md
> docs: add translations to guide/install.md

- .vitepress/config.ts
> fix: fixed issues#215 language link broken

- guide/index.md
> docs: fix translation of guide/index

- features/block-frontmatter.md
- features/build-with-pdf.md
- features/bundle-remote-assets.md
- features/canvas-size.md
- features/click-marker.md
- features/code-block-line-numbers.md
- features/code-block-max-height.md
正在翻 features，希望不会影响到其他人的工作 : )
> docs: add translations to /features(partial)

- features/direction-variant.md
- features/draggable.md
- features/drawing.md
- features/eject-theme.md
- features/frontmatter-merging.md
- features/global-layers.md
**问题描述**:
较为不确定在 'features/direction-variant.md' 中的 navigating 的翻译，我标题直译的，在下面是写的“播放方向”
以及，我保留了 props
辛苦啦
> docs: add translations to 2 more files in /features

- features/plantuml.md
**问题描述**:
update this file features/plantuml.md
> docs: update features/plantuml.md

- builtin/components.md
- guide/exporting.md
> docs: fix translations in builtin/components

- custom/config-parser.md
**问题描述**:
看文档时发现的一个拼写错误，顺手发个 PR...
> chore(typo): Update config-parser.md

- features/mdc.md
**问题描述**:
看文档时发现的一个 url 链接错误，顺手发个 PR
> docs: update features/mdc.md

- custom/index.md
> chore: typo

- README.md
> 📄docs: Update README.md

- guide/animations.md
> fix(v-click): translate error
